# This playbook contains example tasks to perform on a fresh Alpine Linux 
# installation. 
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# All rights reserved. Licensed under CC BY 3.0
#
# Usage: ansible-playbook setup.yml -f 10

---
- hosts: all
  user: root
  tasks:

  - include: tasks/apk-repositories.yml
