# This playbook contains example tasks to perform on a fresh Alpine Linux 
# installation. 
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# All rights reserved. Licensed under CC BY 3.0
#
# Usage: ansible-playbook setup.yml -f 10

---
- hosts: all
  user: root
  vars_files:
    - vars/application-versions.yml

  tasks:
#    - include: tasks/apk-repositories.yml
#    - include: tasks/motd.yml
#    - include: tasks/lighttpd.yml
#    - include: tasks/linfo.yml

  handlers:
   - include: handlers/system.yml
