# This playbook install the PHP Shell detector 
# (https://github.com/emposha/PHP-Shell-Detector).
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: create the 'webapps' directory
  file: path=/usr/share/webapps/
        owner=root
        group=root
        mode=0777
        state=directory

- name: install the git package
  command: /sbin/apk add git

- name: checkout from the php shell detector git repo
  git: repo=git://github.com/emposha/PHP-Shell-Detector.git
       dest=/usr/share/webapps/phpshell-detector

- name: set the right permission
  file: path=/usr/share/webapps/
        mode=0777
        state=directory

- name: create a symlink to the webserver root
  file: src=/usr/share/webapps/phpshell-detector/
        dest=/var/www/localhost/htdocs/phpshell-detector
        owner=root
        group=root
        state=link

- name: remove the git package
  command: /sbin/apk del git
