# This playbook clean the package cache of Alpine Linux hosts.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# All rights reserved. Licensed under CC BY 3.0

---
- hosts: all
  user: root

  tasks:
  - name: clean package cache
    command: /sbin/apk cache clean

