# This playbook updates all Alpine Linux hosts.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# All rights reserved. Licensed under CC BY 3.0

---
- hosts: all
  user: root

  tasks:
  - name: update all packages
    action: command /sbin/apk upgrade -U -a
